- swagger.yaml
adds optional address fields to refusal endpoint, these are only required in the instance where the API is down and the contact centre operative needs to record the address fields due to Case lookup not being available.
Also adds missing reference to uk.gov.ons.responsemanagement.model.server.response.case.CasesContainer which was causing Case object details not to be shown in generated documentation for the /cases/uprn endpoint
> adds optional address fields to refusal endpoint

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseEventDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseRequestDTO.java
- swagger.yaml
This change contains minor modifications to support support CR-86 (which adds get by caseId to Contact Centre).
Changes of significance are:
Mainly:
- Removed id from case event DTO.
- Update error codes returned from the get case by caseId endpoint.
- Updated swagger version.
Run the Contact Centre unit tests.
See CR-86: https://collaborate2.ons.gov.uk/jira/browse/CR-86
> Cr86 retrieve case by case

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTO.java
Removed addressLine4 as it has been decided that it is not needed.
> Removed unused address line

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseEventDTO.java
Updated Case response DTO objects to use Java Date's instead of LocalDateTime.
> Switching from LocalDateTime to just Date

- swagger.yaml
CR70 implements the contact center endpoint for a respondent refusal.
This pull request is to correct the swagger, as it was previously specifying a response which only had the caseid. it now references the correct object type which has the caseid and a timestamp
Only swagger text. 
See: https://collaborate2.ons.gov.uk/jira/browse/CR-70
> CR70 Corrected response for respondent refusal

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/AddressUpdateRequestDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/PostalUnresolvedFulfilmentRequestDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/RefusalRequestDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/SMSUnresolvedFulfilmentRequestDTO.java
Removed all remaining references to 'addressLine4'. These were restricted to several request DTO's which still had an addressLine4 field.
See: https://collaborate2.ons.gov.uk/jira/browse/CR-70
> CR70 Removed address line 4 from DTO objects

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/model/UniquePropertyReferenceNumber.java
Fix to make Jackson serialise the value for uprn without an extra level in the serialised string.
> CR289 Fix for json serialisation to string

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/model/UniquePropertyReferenceNumber.java
Added Jackson annotation to force serialisation to convert the long uprn value to a string.
Here is the output from a manual test. Note the double quotes around the uprn value:
```
> curl -s -H "Content-Type: application/json" --user $CC_USERNAME:$CC_PASSWORD "$CC/cases/9347a654-4f13-11e9-8647-d663bd873d93?case-events=true" | jq | head -15
{
"id": "9347a654-4f13-11e9-8647-d663bd873d93",
"caseRef": "123123",
"caseType": "HH",
"createdDateTime": "2019-04-14T13:45:26.564+01:00",
"addressLine1": "Napier House",
"addressLine2": "11 Park Street",
"addressLine3": "Parkhead",
"townName": "Glasgow",
"region": "E",
"postcode": "G1 2AA",
"uprn": "1347459999",
"caseEvents": null
}
```
https://collaborate2.ons.gov.uk/jira/browse/CR-289
> CR289 Fix to force Jackson to serialise the uprn as a string

- swagger.yaml
The POST /addresses/{UPRN} endpoint described in the swagger spec existed to allow address modifications, address type changes, new addresses and updating address to mark them as invalid. The categories and types within that endpoint did not map well to RMs internal events AddressTypeChanged, AddressModified and AddressNotValid. In addition the Events all  require a case id including in the message.
This pull request removes the address modification endpoint POST /addresses/{UPRN}  and replaces it with POST /cases/{caseId}/address. A new category set has been added that makes clear the intended internal event type for the chosen category. The new categories are...
- ADDRESS_MODIFIED_NEW
- ADDRESS_MODIFIED_UPDATE
- ADDRESS_INVALID_DERELICT
- ADDRESS_INVALID_DEMOLISHED
- …
> changes swagger spec address update end point to case update

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/AddressDTO.java
Amend Contact Centre API to add the attributes countryCode, addressType and estabType to the results for an address search by postcode or address string.
Addition of required attributes to AddressDTO representation.
Unit tests changed as required in Census Contact Centre Service repository interdependent [PR](https://github.com/ONSdigital/census-contact-centre-service/pull/34) which implements address search with new attributes added. Running the Contact Centre may be tested in Postman by issuing appropriate URL e.g. /addresses/postcode?postcode=EX1+2NP or addresses?input=5+Summerland+Gate+Belgrave Road+Exeter
The Address Index Service has not yet implemented these additional attributes in the search results. The attributes will always be null until they send these attributes in the …
> CR-643 Add countryCode, addressType, estabType to address search result

- .gitignore
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/FulfilmentDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/FulfilmentsRequestDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/ProductGroup.java
This  change is required to allow the contact centre service to use the latest version (1.0.1) of the product reference library and to meet the requirements from card CR-737.
See swagger spec in GH census-contact-centre-service-api/swagger.yml
> Update with new product reference fields

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTO.java
A simple change to add the 'allowedDeliveryChannels' attribute to the CaseDTO, as per the swagger spec
> add 'allowedDeliveryChannels' attribute to the CaseDTO

- .gitignore
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTO.java
I have added the addressType field to the CaseDTO, which is the response body that Serco receive when they call any of the three GET case endpoints in the CCSVC.
> Add addressType to CaseDTO

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTO.java
Amend Contact Centre Service API to add the attributes estabType and estabDescription to the results for a Case search by Id, caseRef or UPRN.
Addition of required attributes to CaseDTO representation.
Unit tests changed as required in Census Contact Centre Service repository. To be delivered when this dependency is available as a Release version.
> CR-937 EstabType and EstabDescription added to CaseDTO

- pom.xml
- swagger-current.yml
Cucumber tests have been using DTOs from contactcentreserviceapi in order to map requests to and responses from CCService. DTOs should be generated using a Swagger spec and then compiled and run as part of the tests. This ensures that tests are decoupled from production code as much as possible and also the Swagger spec correctly reflects the state of the service in question.
Added the swagger-current.yml as a resource when packaging the jar
Made minor changes to the swagger spec to fix a couple of minor errors.
This project is a dependency of Contact-centre-service and so building and testing CCServ along with running the cucumber tests will validate its integrity.
https://collaborate2.ons.gov.uk/jira/browse/CR-925
> Cr 925 add swagger to cucumber test

- swagger-future.yml
This change reduces the differences between swagger-current and swagger-future.
It doesn't have any changes of substance and just aims to make comparing the 2 versions easier.
> CR_0 Fix formatting differences with swagger-current

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/RefusalRequestDTO.java
- swagger-current.yml
- swagger-future.yml
CR-985 requires a call-Id to be added to the Refusal DTO
Also, the swagger-future YAML  was missing the calId section , so that was added. And the relevant callId parts were added to the swagger-current YAML.
> CR-985 add callId to to refusal DTO

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/Constants.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/NewCaseRequestDTO.java
- src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTOTest.java
- swagger-current.yml
UPRNs generated for skeleton cases by RM have an additional leading digit, needing to allow for 13 digits.
POM dependencies changed to include new UniquePropertyReferenceNumber allowing for 13 digits.
Contants static attributes never used and duplicated in UniquePropertyReferenceNumber removed.
NewCaseRequestDTO altered to use UniquePropertyReferenceNumber as opposed to String for UPRN.
Unit test adjusted with 13 rather than 12 digit value.
https://github.com/ONSdigital/census-int-common-service/pull/44
> CR-1047 Extend UPRN validation to allow 13 digits.

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseRequestDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/ModifyCaseRequestDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/NewCaseRequestDTO.java
- swagger-current.yml
CR-973 requires changes to the DTO classes support the PUT case for modification endpoint. The swagger is also updated to match.
- relevant parts of future swagger copied to current swagger
- DTO objects supporting address modification or type change are modified to fit requirement
> Cr 973 put case endpoint

- swagger-current.yml
Updating version number is swagger-current. 
Missed this earlier and Rob only spotted it after the previous PR was merged.
> CR-1063 Updating version number of current swagger

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/UACRequestDTO.java
Adjust DTO to conform to swagger spec for AD operative to obtain a UAC for a caseId. 
Minor change to UACRequestDTO required for implementation in census-contact-centre-service.
> CR-809_Add_AD_get_UAC_endpoint

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/RefusalRequestDTO.java
- swagger-current.yml
- swagger-future.yml
Refusals endpoint no longer supports the 'unknown' caseId.
The knockon impact of this is the caseId can now become a UUID instead of a String.
Swagger documentation updated to reflect these changes.
> Cr 1160 removed unknown from refusuals endpoint

- swagger-current.yml
- swagger-future.yml
The EstabType has been update in census-int-common-service as per the list given on confluence: https://collaborate2.ons.gov.uk/confluence/display/SDC/SERCO+-+Estab+Type+List. 
Updating the current and future swagger files accordingly.
For more details on the changes in census-int-common-service please have a look at https://collaborate2.ons.gov.uk/jira/browse/CR-1208.
> CR-1208 | updating estabType in swagger files as per updated confluence document

- API.md
Explanatory text added for endpoint to update the address details for a known case and/or report a change of establishment type.
As no alteration to API details in swagger, only supplement to explanatory text in markup file have not incremented version.
> CR-1201 Explanatory text for updating case details

- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/AddressQueryRequestDTO.java
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/PostcodeQueryRequestDTO.java
- swagger-current.yml
- swagger-future.yml
To allow Serco to get more than 250 address.
Updated the maximum value of offset and limit to 5000.
Changed the current and future swagger accordingly.
https://collaborate2.ons.gov.uk/jira/browse/CR-1167
> CR-1167 Updated max values of offset and limit to 5000

- pom.xml
- src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/PostalFulfilmentRequestDTO.java
- swagger-current.yml
- swagger-future.yml
The max field lengths of title, forename and surname in PostalFulfilmentDTO and its swagger representations are wrong.
They were 16, 60, 60 and should be 20, 35, 35 characters in length respectively
PostalFulfilmentDTO - amended field sizes
swagger-current.yml - amended field sizes
swagger-future.yml - amended field sizes
Updated POM dependencies
This build will be pushed and its dependency will be updated in CCSERV and CCCUC
The Unit tests in CCServ will be run
The Cumber tests will be run
> Cr 1605 change max field values for postal fulfilments
