src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/AddressQueryRequestDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/PostcodeQueryRequestDTO.java

Adding toString to DTO to help with debugging.
Part of CR65, which is adding address and postcode queries:https://collaborate2.ons.gov.uk/jira/browse/CR-65?filter=-1

CR65 Added toString annotation to help with logging

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/AddressUpdateRequestDTO.java

Added a new DTO object to support the /addresses/uprn endpoint.

CR180 Added DTO to support /addresses/uprn endpoint

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseType.java

CR-232 H->HH etc

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/model/UniquePropertyReferenceNumber.java
swagger.yaml

Added uprn to case DTO
https://collaborate2.ons.gov.uk/jira/browse/CR-289

Added uprn to case dto

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/model/UniquePropertyReferenceNumber.java

Actually delivered fix for json serialisation bug this time!

CR289 Fix for json serialisation to string

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/AddressUpdateRequestDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/AppointmentRequestDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/PostalFulfilmentRequestDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/PostalUnresolvedFulfilmentRequestDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/RefusalRequestDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/SMSFulfilmentRequestDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/SMSUnresolvedFulfilmentRequestDTO.java

redacted personal info fields from potential logging

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/AddressDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/AddressUpdateRequestDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/PostalUnresolvedFulfilmentRequestDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/RefusalRequestDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/SMSUnresolvedFulfilmentRequestDTO.java

tweaked logging

---

pom.xml

Needs to pick up latest changes in int-common-service This is used by dependent projects.
Changed version of int-common-service in pom.xml
run unit tests mvn clean install
Changed UPRN class is used by dependent project - contact-centre-cucumber

Incremented version of int-common-service

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/LaunchRequestDTO.java

Added attribute to launch eq request payload, so that Serco can tell us if the request is or is not on behalf of an individual.

CR_648 Added individual attribute for launch request payload

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/Constants.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/SMSFulfilmentRequestDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/SMSUnresolvedFulfilmentRequestDTO.java

CR-579 telephone regex validation change

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTO.java
src/test/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTOTest.java

Add secureEstablishment and estabUprn to the CaseDTO class.  Added unit test to prove no interfering of UPRN elements.

Cr 831 secure establishment added to case

---

swagger.yaml

CR-955 Removed INVITE from fulfilments query

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/AddressDTO.java

CR-807 Added estab description to the address DTO

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTO.java

Minor enhancement to add lastUpdated to CaseDTO returned to Contact Centre now returned in Case Service requests
Attribute lastUpdated added to CaseDTO.

CR-811 Fulfilments endpoints

---

pom.xml
swagger-5.11.4.yml

Added dependency message for contact-center-cucumber
swagger-5.11.3.yml updated to swagger-5.11.4.yml adding swagger-current.yml changes
There is no test for the advertised version, but the swagger-current.yml can be tested using the 
contact-centre-cucumber tests

updated advertised version of swagger.yml

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseRequestDTO.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/NewCaseRequestDTO.java
swagger-current.yml
swagger-future.yml

This change updates the swagger to match the description of the new case endpoint from CR-957. 
The pom is also updated to use the latest framework and test-framework.

Cr 957 update objects for new case creation

---

src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/CaseDTO.java
swagger-current.yml

organisation name needs to be returned in the CaseDTO from the 3 CCSvc endpoints.

CR-983 add ceOrgName to CaseDTO

---

pom.xml
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/Constants.java
src/main/java/uk/gov/ons/ctp/integration/contactcentresvc/representation/RefusalRequestDTO.java
swagger-current.yml

Updates to the contents of a CC refusal recieved request:
- Removed notes
- Removed telephone number 
- Added isHouseholder flag

Cr 1063 upadate fields for refusal recieved

---

swagger-current.yml
swagger-future.yml

Removed text which said that the title is required in an individual postal fulfilment request.

CR-1305 Updated swagger

---

pom.xml

CR-1258 | updating dependency version
